MODEL = "mistralai/Mixtral-8x7B-Instruct-v0.1"
STORY_STRUCTURE_PATH = "textFiles/storyStructures"
THEME_PATH = "textFiles/themes"
SCHEMA_FOR_JSON_SCHEMA = "http://json-schema.org/draft-07/schema#"
ERRORS_PATH = "textFiles/errors"
